
volumes:
  db_volume:

networks:
  tr_network:
    name: tr_network
    driver: bridge

services:
  tr_back:
    build: srcs/backend
    image: tr_back
    container_name: tr_back
    volumes:
        - ./srcs/backend:/app
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_PORT=${DJANGO_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=UTC
    networks:
      tr_network:
        aliases:
          - tr-back
    ports:
        - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - tr_db
  tr_db:
    image: postgres:17.3-alpine3.21
    container_name: tr_db
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=UTC
    networks:
      tr_network:
        aliases:
          - tr-db
    expose:
      - ${POSTGRES_PORT}
    restart: always